
version: 2

models:
    - name: joined_tables
      description: "A starter dbt model for Polygon"
      columns:
          - name: block_number
            description: "block number of transaction"
            tests:
                - not_null
